---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-cns-app
  labels:
    app.kubernetes.io/name: ai-cns-app
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: ai-cns-app
    creationPolicy: Owner
  data:
  - secretKey: SLACK_CLIENT_SECRET
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_LUBAIN_SLACK_CLIENT_SECRET
  - secretKey: SLACK_SIGNING_SECRET
    remoteRef:
      key: ai-cns-app-secrets
    property: CHARACTER_LUBAIN_SLACK_SIGNING_SECRET
  - secretKey: SLACK_BOT_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_LUBAIN_SLACK_BOT_TOKEN
  - secretKey: SLACK_VERIFICATION_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_LUBAIN_SLACK_VERIFICATION_TOKEN
  - secretKey: CHARACTER_VITALAIK_SLACK_CLIENT_SECRET
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_VITALAIK_SLACK_CLIENT_SECRET
  - secretKey: CHARACTER_VITALAIK_SLACK_SIGNING_SECRET
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_VITALAIK_SLACK_SIGNING_SECRET
  - secretKey: CHARACTER_VITALAIK_SLACK_BOT_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_VITALAIK_SLACK_BOT_TOKEN
  - secretKey: CHARACTER_VITALAIK_SLACK_VERIFICATION_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_VITALAIK_SLACK_VERIFICATION_TOKEN
  - secretKey: CHARACTER_SATOSHAI_SLACK_CLIENT_SECRET
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_SATOSHAI_SLACK_CLIENT_SECRET
  - secretKey: CHARACTER_SATOSHAI_SLACK_SIGNING_SECRET
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_SATOSHAI_SLACK_SIGNING_SECRET
  - secretKey: CHARACTER_SATOSHAI_SLACK_BOT_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_SATOSHAI_SLACK_BOT_TOKEN
  - secretKey: CHARACTER_SATOSHAI_SLACK_VERIFICATION_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: CHARACTER_SATOSHAI_SLACK_VERIFICATION_TOKEN
  - secretKey: EVM_PRIVATE_KEY
    remoteRef:
      key: ai-cns-app-secrets
      property: EVM_PRIVATE_KEY
  - secretKey: EVM_PROVIDER_URL
    remoteRef:
      key: ai-cns-app-secrets
      property: EVM_PROVIDER_URL
  - secretKey: EVM_PUBLIC_KEY
    remoteRef:
      key: ai-cns-app-secrets
      property: EVM_PUBLIC_KEY
  - secretKey: LINEA_SEPOLIA_RPC_URL
    remoteRef:
      key: ai-cns-app-secrets
      property: LINEA_SEPOLIA_RPC_URL
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: ai-cns-app-secrets
      property: OPENAI_API_KEY
  - secretKey: SUPABASE_ANON_KEY
    remoteRef:
      key: ai-cns-app-secrets
      property: SUPABASE_ANON_KEY
  - secretKey: TELEGRAM_BOT_TOKEN
    remoteRef:
      key: ai-cns-app-secrets
      property: TELEGRAM_BOT_TOKEN
